### ISSUE TITLE
Some ways to store fired query/result

### ISSUE THREAD

**Issue by michaelthwan** [michaelthwan/searchGPT#33]
So that we may analyze users' input

**Comment by eren23** [comment]
hey, what's in mind here, like a browser storage for users to use it somehow or storing everyone's requests in a central DB after making users accept an agreement, mongo etc.?

**Comment by michaelthwan** [comment]
Yes. Tested with gsheets but it is too difficult to auth (need oauth)
I will now use Firebase. (the code will only enable in searchgpt-demo repository which is private.)

**Comment by eren23** [comment]
Thanks a lot for the response, sounds like a good plan and the outputs are really showing potential it seems from what you wrote  :)

**Comment by michaelthwan** [comment]
Thank you @eren23 
And the issue is done.
