### ISSUE TITLE
Remove character limit

### ISSUE THREAD

**Issue by CactiStaccingCrane** [michaelthwan/searchGPT#52]
When I type search terms such as "spacex" and "apple", searchGPT doesn't allow that. To me this is pretty limiting and force the users to make the search term much longer than it should be.

**Comment by michaelthwan** [comment]
Hi @CactiStaccingCrane thanks for your input. My intention to add the validation is that searchGPT works better using natural language queries. But I may let user like you to decide what to input. I will make it into 5-200 char later.

**Comment by michaelthwan** [comment]
Hello @CactiStaccingCrane 
#53 PR updated min char as 5. See if it enable more options for you. Deployed
https://searchgpt-demo.herokuapp.com/
